### ISSUE TITLE
Freezes Only First Middleware Instance (or Application if No Middleware)

### ISSUE THREAD

**Issue by jeremyevans** [ioquatix/rack-freeze#1]
rack-freeze appears to freeze the rack application (set using `Builder#run`) if no middleware are used, or only the first middleware instance, as `Builder#to_app` returns the application itself or first middleware instance:

```ruby
x = proc{}
Rack::Builder.new{run x}.to_app == x
# => true
Rack::Builder.new{use Rack::CommonLogger; run x}.to_app == x
# => false
Rack::Builder.new{use Rack::CommonLogger; run x}.to_app
# => #<Rack::CommonLogger:0x0008132b414510 @app=#<Proc:0x0008132b415a28@(irb):3>, @logger=nil>
Rack::Builder.new{use Rack::CommonLogger; use Rack::Lint; run x}.to_app
# => #<Rack::CommonLogger:0x00081317000460 @app=#<Rack::Lint:0x00081317000488 @app=#<Proc:0x000812e51f7a20@(irb):4>, @content_length=nil>, @logger=nil>
```

I'm guessing the intent is that rack-freeze should freeze all middleware instances used, not just the first one, and should either always freeze the rack application or never freeze the rack application for consistency.  My vote would be always freeze the rack application, but that's more likely to break things.

I apologize if I'm off base here, I didn't actually try rack-freeze, just inspected the code and specs.  If I'm wrong, it would probably be worth at least adding specs for the no middleware and multiple middleware cases.

**Comment by ioquatix** [comment]
You are right to query this. It's recursive and it depends on middleware doing the right thing if they implement their own #freeze

I will make a spec to show this.

**Comment by jeremyevans** [comment]
Even if a middleware doesn't implement a custom `freeze`, this can still break. The `freeze` method you add will only work if the next middleware is stored in an instance variable (granted, most middleware store the next middleware in an instance variable).  It will break for a middleware such as:

```
class Foo
  def initialize(app); @app = [app] end
  def call(env); @app.first.call(env) end
end
```

The `freeze` method you use is also fairly dangerous, consider:

```
class Foo
  def initialize(app); @app = app; @object = Object end
  def call(env); @app.call(env) end
end
```

Overriding `freeze` for a class you don't control is dangerous. You should assume `freeze` is already implemented correctly and not override it.  If `freeze` doesn't work correctly for a middleware, file a bug with the middleware's maintainer.

**Comment by jeremyevans** [comment]
Looking at the rack code, you probably want to do something like:

```
    def to_app
      app = @map ? generate_map(@run, @map) : @run
      fail "missing run or map statement" unless app
      app = @use.reverse.inject(app.freeze) { |a,e| e[a].freeze } # <= freeze each middleware
      @warmup.call(app) if @warmup
      app
    end
```

That's basically the current version of rack with a couple freeze calls added.  It hasn't been modified in the last four years, so it should be fairly stable.

**Comment by ioquatix** [comment]
@jeremyevans These are all good points.

I want to summarise: *Essentially, there are a number of different ways to ensure middleware is frozen, all with different trade-offs.* I've considered the issues you raise above, and the alternative solution of directly replacing `to_app`. I think that they have different trade-offs, and that semantically what I've done is simpler.

## Why modify to_app to freeze individual middleware does not always work

It sounds like you are asserting that modifying `to_app` may be a better approach. However, it's still possible that this will not work.

```ruby
# e.g. for conditional invocation, really just an example that it's semantically possible.
class Wrapper
    def initialize(app, middleware)
        @app = app
        @middleware = middleware.new(app)
    end
end

Builder.new do
    use Wrapper, SomeOtherMiddleware
end
```

### Achieve the same thing with less invasion

It would be trivial to make `Builder#use` wrapper, when `#new` is called, calls the wrapped class `#new` and then invoke `#freeze` on the result. This way, don't need to modify the semantics of `to_app`.

```ruby
class Freezer
    def initialize(*args, &block)
        @klass, *@args = args; @block = block
    end

    def new
        @klass.new(*@args, &@block).freeze
    end
end

#... Builder
def use(*args, &block)
    return Freezer.new(*args, &block)
end
```

## On the nature of automatically generating `#freeze`

I agree on this point that it's risky. I like the idea that people would adopt the policy of frozen middleware. But, I don't see that happening in general unless people see significant benefit to the approach. In any case, this gem provides the policy and implements it in a generic way where possible. If it doesn't work for some specific middleware, let's try to figure out why and make sure it works, and in addition ask the author to add a proper `#freeze` method.

The main point you raise is that it might do weird things like call `Object#freeze`. Unfortunately, I don't see that there is any way around this in general, except perhaps to improve the implementation of the auto-`#freeze` method. It could be that it only calls freeze on things which would be safe (e.g. establish a list of classes which can call freeze on).

With respect to things like Array and Hash. Personally, I think it makes sense for these to be frozen, and their contents too. However, I'm on the fence about this. For me, I'd prefer to use a separate gem for "deep freeze". In the end, it's a balance between trying to establish the policy ("I think everyone should implement `#freeze` on their middleware according to this semantic"), and applying in in a generic way to middleware which doesn't support it explicitly ("I accept you don't want to implement `#freeze` so we will manually implement it in a way that is sufficient for detecting potential bugs").

**Comment by ioquatix** [comment]
So, I do actually like the idea of having a `Freezer` wrapper which manually calls freeze on the middleware when it's instantiated. It's less invasive. What do you think? @jeremyevans

**Comment by jeremyevans** [comment]
I don't think there's a big difference between whether you override `to_app` or `use`, or if you use `Freezer`, as long as each middleware and the rack application is frozen.  Note that modifying `use` without `to_app` won't freeze the rack application, and I doubt it will correctly handle `map`.

I'm not sure how the `Builder#use` example you show would work as it doesn't modify `@use`, and I'm not sure how how overriding `use` would be better than `to_app` as I showed in my example. Wouldn't the behavior of the `Wrapper` example you give be the same with both?

The important part is really removing your overriding of the `freeze` method.  There's a good reason freezing all instance variables isn't ruby's default behavior when calling `Kernel#freeze`, and forcing that behavior on all middleware classes that don't override `freeze` can break things.

Another recommendation would be instead of prepending to `Rack::Builder`, design this to be used with `extend`:

```ruby

require 'rack/freeze'
extend Rack::Freeze

use Rack::CommonLogger

require './app'
run App
```

That way you only modify the specific `Rack::Builder` instance where you want to change the behavior, instead of all `Rack::Builder` instances.

**Comment by ioquatix** [comment]
So, the last part of this discussion, is whether *this semantic* should still exist:

https://github.com/ioquatix/rack-freeze/blob/f23fd5e1670128992513fdac6a471838e3fe7481/lib/rack/freeze/freezer.rb#L47-L49

@jeremyevans what do you think? It seems like you'd vote for it NOT to do this?

**Comment by jeremyevans** [comment]
@ioquatix Yes, I believe that is a bad idea.  Freezing the middleware instance is fine, freezing each of its instance variables is not.

**Comment by ioquatix** [comment]
As this is now implemented by the `Freezer` wrapper, it's no longer necessary to freeze instance variables, so I can remove this logic easily.

**Comment by ioquatix** [comment]
How would it work with `extend`?

**Comment by jeremyevans** [comment]
Note that if you want to freeze the rack application in addition to the middleware, I think you'll need to override `to_app` as I showed or override `run` (consider the case with no middleware).  Also, if you want to handle `map` correctly, you'll probably need to override `generate_map` if you don't override `to_app` as I showed.

For `extend`, you would remove `Builder.prepend(Freeze::Builder)` and after `require 'rack/freeze'`, you would call `extend Rack::Freeze::Builder` inside `Builder#new`/`config.ru` (see example in earlier comment, but using `Rack::Freeze::Builder` instead of `Rack::Freeze`).  If a user really wanted all `Rack::Builder` instances to be modified, they could always call `Rack::Builder.prepend` manually.

**Comment by ioquatix** [comment]
Okay, so I think we are good on all your suggestions, except for one.

I like the idea that `require 'rack/freeze'` implements a global policy, even thought generally I dislike such approaches. I've made it that so if you don't want global policy, you can simply write `require 'rack/freeze/builder'` and use `extend` manually. What do you think?

**Comment by ioquatix** [comment]
The main benefit of global policy by default is that this isn't so much a new "feature", but applying a run-time policy to existing code without any changes. If this were adding a new feature, I wouldn't be adding it by default. There is hardly any other use-case for this library.

**Comment by jeremyevans** [comment]
I think that's a good approach as it is simple for the general use case, while still allowing for more control.

**Comment by ioquatix** [comment]
@jeremyevans thanks for all your feedback and the time you've taken to discuss ideas and improve code.
