### ISSUE TITLE
How to use this on rails application without error?

### ISSUE THREAD

**Issue by PikachuEXE** [ioquatix/rack-freeze#4]
I tried to use this gem but I got error due to rails code lazying loading stuff:

## The error
```
App 10285 stderr: [ 2017-04-03 14:04:33.2507 10319/0x007fec20701b60(Worker 1) utils.rb:87 ]: *** Exception RuntimeError in Rack application object (can't modify frozen #<Class:#<Spacious::Application:0x007fec26b13680>>) (process 10319, thread 0x007fec20701b60(Worker 1)):
App 10285 stderr: 	from /users/pikachuexe/.rvm/gems/ruby-2.3.4/gems/railties-5.0.2/lib/rails/engine.rb:527:in `env_config'
App 10285 stderr: 	from /users/pikachuexe/.rvm/gems/ruby-2.3.4/gems/railties-5.0.2/lib/rails/application.rb:248:in `env_config'
App 10285 stderr: 	from /users/pikachuexe/.rvm/gems/ruby-2.3.4/gems/railties-5.0.2/lib/rails/engine.rb:693:in `build_request'
App 10285 stderr: 	from /users/pikachuexe/.rvm/gems/ruby-2.3.4/gems/railties-5.0.2/lib/rails/application.rb:521:in `build_request'
App 10285 stderr: 	from /users/pikachuexe/.rvm/gems/ruby-2.3.4/gems/railties-5.0.2/lib/rails/engine.rb:521:in `call'
App 10285 stderr: 	from /users/pikachuexe/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.0.0.332/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
App 10285 stderr: 	from /users/pikachuexe/.rvm/gems/ruby-2.3.4/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
App 10285 stderr: 	from /users/pikachuexe/.rvm/gems/ruby-2.3.4/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
App 10285 stderr: 	from /users/pikachuexe/.rvm/gems/ruby-2.3.4/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
App 10285 stderr: 	from /users/pikachuexe/.rvm/gems/ruby-2.3.4/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
App 10285 stderr: 	from /users/pikachuexe/.rvm/gems/ruby-2.3.4/gems/passenger-5.1.2/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

## The rails source code
https://github.com/rails/rails/blob/5-0-stable/railties/lib/rails/engine.rb#L527

What should be done to get rid of the error?

**Comment by ioquatix** [comment]
Yes, and what this is indicating is that you've got a bug in your code that will likely fail in a multi-threaded environment.

**Comment by ioquatix** [comment]
This is telling you that you've found a bug that could be a race condition in a multi-threaded environment.

The solution is to not lazy initialise that parameter, or to implement your own freeze and call that function before freezing the object.

**Comment by ioquatix** [comment]
Assuming that this is fixed/no longer relevant.

**Comment by divyesh2506** [comment]
@PikachuEXE How did you get it fixed?  
I'm getting a similar exception.

**Comment by ioquatix** [comment]
You would need to track down the code which is trying to modify something which should be frozen - if it's shared between workers/threads it will be a race condition.

**Comment by mshiltonj** [comment]
The code in the stacktrace is inside the rails engine. I'm getting it as well w/o any mounted engines or added middleware. Does this mean vanilla rails can't work the rack_freeze gem?

I'm running rails 5 (for now), but rails 6 also does ||= for env_config in engine.rb at:

https://github.com/rails/rails/blob/0c3e02cb520a1a7a913dd76d631bea03d6dd9764/railties/lib/rails/engine.rb#L544

**Comment by mshiltonj** [comment]
using rails 5 or 6:

rails new foo
cd foo
bundle add rack-freeze
rails s

go to localhost 3000 and see a frozen string error
