### ISSUE TITLE
Any advice on how to use this with Rails?

### ISSUE THREAD

**Issue by ghiculescu** [ioquatix/rack-freeze#6]
https://github.com/rack/rack/pull/1149#issuecomment-290922594 hinted at the fact that Rails doesn't use `Rack::Builder`.

I've tried the steps in the readme, and am still able to run middleware that mutates state on each request.

Just wondering if you have any advice on how to run this (or something similar) on a Rails 4 (or 5 if that's easier, we are about to upgrade) app?

**Comment by ioquatix** [comment]
Hey, sorry I never replied.

Well, I don't know how rails works. But my guess is, if you try to apply this gem, it will break.

Rails almost certainly has some kind of middleware stack.

https://github.com/rails/rails/blob/1518ce3dc8dc092a32cf1020ff7c67f2337b3993/actionpack/lib/action_dispatch/middleware/executor.rb

But they'd need to adopt a similar policy of frozen controllers, views, etc. Unfortunately, this is way out of the scope of this gem.
